spring.application.name=SpringBoot
# Server Configuration
server.port=8080
# Logging
logging.level.org.springframework=INFO

# Database Configuration for H2
spring.datasource.url=jdbc:h2:mem:demoDatabase
spring.jpa.show-sql=true

#to delay data initialization, first create table and then update data
spring.jpa.defer-datasource-initialization=true

# Database Configuration for PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_database
#spring.datasource.username=nidhi_20
#spring.datasource.password=Nidz@1005
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


